export const pricingPackages = [
  {
    id: "consultation",
    name: "Free Consultation",
    price: "Free",
    description: "30-minute strategy session to discuss your project",
    category: "consultation" as const,
    featured: false,
    features: [
      "Project requirements analysis",
      "Technology stack recommendations",
      "Timeline and budget estimation",
      "Strategic planning advice",
      "No obligation quote",
    ],
  },
  {
    id: "website-basic",
    name: "Website - Basic",
    price: "KES 375,000",
    description: "Perfect for small businesses and startups",
    category: "website" as const,
    featured: false,
    features: [
      "Up to 5 pages",
      "Responsive design",
      "Content management system",
      "Contact form integration",
      "SEO optimization",
      "2 rounds of revisions",
      "3 months support",
    ],
  },
  {
    id: "website-pro",
    name: "Website - Professional",
    price: "KES 750,000",
    description: "Advanced features for growing businesses",
    category: "website" as const,
    featured: true,
    features: [
      "Up to 15 pages",
      "Custom design & animations",
      "Advanced CMS integration",
      "E-commerce capabilities",
      "API integrations",
      "Advanced SEO & analytics",
      "5 rounds of revisions",
      "6 months support",
    ],
  },
  {
    id: "website-enterprise",
    name: "Website - Enterprise",
    price: "Custom Quote",
    description: "Full-scale solutions for large organizations",
    category: "website" as const,
    featured: false,
    features: [
      "Unlimited pages",
      "Custom features & integrations",
      "Multi-language support",
      "Advanced security features",
      "Performance optimization",
      "Dedicated project manager",
      "Unlimited revisions",
      "12 months support",
    ],
  },
  {
    id: "software-custom",
    name: "Custom Software",
    price: "Custom Quote",
    description: "Tailored software solutions for your business",
    category: "software" as const,
    featured: false,
    features: [
      "Requirements analysis & planning",
      "Custom architecture design",
      "Scalable infrastructure",
      "Database design & optimization",
      "API development",
      "User authentication & security",
      "Testing & quality assurance",
      "Deployment & maintenance",
    ],
  },
  {
    id: "additional-services",
    name: "Additional Services",
    price: "Variable",
    description: "Ongoing support and maintenance",
    category: "additional" as const,
    featured: false,
    features: [
      "Monthly maintenance - from KES 30,000/mo",
      "Hosting & domain management",
      "Content updates",
      "Performance monitoring",
      "Security updates",
      "Technical support",
      "Training & documentation",
    ],
  },
];
